### ISSUE TITLE
Questions for the implementation of hierarchical sampling

### ISSUE THREAD

**Issue by alvin319** [facebookresearch/ssl-data-curation#7]
Thank you so much for writing the paper and open-sourcing the implementation!

Section 3.3 of the paper introduces the hierarchical sampling method, corresponding to the functions I've linked below.

https://github.com/facebookresearch/ssl-data-curation/blob/f5405376435b0b8ff46c440bc3fdb2d34ac1bd1f/src/hierarchical_sampling.py#L138-L154C36

I'm currently learning more about the implementations and have a couple of observations/questions I'd like to understand better.

1. Where is the sampling strategy for the furthest `f` points from the centroids?
2. If we're at the last level of the clustering, why do we want to repeat the number of samples in the cluster via `np.tile` if the current cluster size is bigger than the target size? Moreover, it seems like we're selecting the remainder of the samples with the sampling strategy and concatenating that with the repeated samples.

**Comment by huyvvo** [comment]
Hello, thank you for your interest in our work!

For your questions:
  1. `f' strategy is not included in the current implementation since it is bad but you can enable it by adding an option in the function `recursive_hierarchical_sampling`. For example:

```
elif sampling_strategy == "f":  # "furthest"
    remaining_samples = current_cluster[-remaining_target :]
```
  2. The current implementation of the hierarchical sampling is more general than what was discussed in the paper. It allows for duplicates in sampled subsets via the parameter `multiplier`, hence the use of `np.tile`. In the default case when `multiplier == 1`, we do not repeat samples and we always guarantee that `target_size <= current_cluster_size`.

**Comment by alvin319** [comment]
> Hello, thank you for your interest in our work!
> 
> For your questions:
> 
> 1. `f' strategy is not included in the current implementation since it is bad but you can enable it by adding an option in the function `recursive_hierarchical_sampling`. For example:
> 
> ```
> elif sampling_strategy == "f":  # "furthest"
>     remaining_samples = current_cluster[-remaining_target :]
> ```
> 
> 2. The current implementation of the hierarchical sampling is more general than what was discussed in the paper. It allows for duplicates in sampled subsets via the parameter `multiplier`, hence the use of `np.tile`. In the default case when `multiplier == 1`, we do not repeat samples and we always guarantee that `target_size <= current_cluster_size`.

Thanks for the quick response -- how do you exactly guarantee that`target_size <= current_cluster_size`? Did you pick the `target_size` based on the cluster membership distribution?

**Comment by huyvvo** [comment]
> Thanks for the quick response -- how do you exactly guarantee that `target_size <= current_cluster_size`? Did you pick the `target_size` based on the cluster membership distribution?

Indeed, the `target_size` corresponding to each cluster is computed based on the cluster's size as you can see in functions `_find_best_cut_left` and `find_subcluster_target_size`.

**Comment by alvin319** [comment]
> > Thanks for the quick response -- how do you exactly guarantee that `target_size <= current_cluster_size`? Did you pick the `target_size` based on the cluster membership distribution?
> 
> Indeed, the `target_size` corresponding to each cluster is computed based on the cluster's size as you can see in functions `_find_best_cut_left` and `find_subcluster_target_size`.

I see, but how do you determine the `target_size` from the `run_hierarchical_sampling.py`? More specifically, it seems like we have that as an argument, and for each cluster, we run a binary search to find the optimal target size based on the constraint mentioned in the paper.

**Comment by huyvvo** [comment]
> I see, but how do you determine the target_size from the run_hierarchical_sampling.py? More specifically, it seems like we have that as an argument, and for each cluster, we run a binary search to find the optimal target size based on the constraint mentioned in the paper.

Yes, we have the target size of the curated dataset as an argument in run_hierarchical_sampling.py. As explained in the paper, we use binary search to find the target size corresponding to each cluster, i.e. the number of points to sample from each cluster, in the highest level. The we repeat this process recursively all the way down to level 1. By default, without allowing duplicates in the curated dataset, i.e. `multiplier = 1`, we require that the initial target size does not exceed the raw data pool's size.

**Comment by alvin319** [comment]
> > I see, but how do you determine the target_size from the run_hierarchical_sampling.py? More specifically, it seems like we have that as an argument, and for each cluster, we run a binary search to find the optimal target size based on the constraint mentioned in the paper.
> 
> Yes, we have the target size of the curated dataset as an argument in run_hierarchical_sampling.py. As explained in the paper, we use binary search to find the target size corresponding to each cluster, i.e. the number of points to sample from each cluster, in the highest level. The we repeat this process recursively all the way down to level 1. By default, without allowing duplicates in the curated dataset, i.e. `multiplier = 1`, we require that the initial target size does not exceed the raw data pool's size.


Thanks for the clarification! I have one last question 😅. Since the over-sampling with the `multiplier` parameter is not mentioned in the paper, are there any interesting observations w.r.t. the curation quality?

**Comment by huyvvo** [comment]
In our experiments, we set `multiplier` greater than `1` and increase `target_size` as many times to obtain a curated dataset that is equivalent to a concatenation of `multiplier` curated datasets with size `target_size`. This is conceptually better since it increases the dataset's diversity. However, it does not lead to significant difference compared to the default setting.
